services:
  dwh_pipeline:
    build:
      context: .
      dockerfile: Dockerfile.dwh
    container_name: dwh_pipeline
    env_file:
      - .env
    environment:
      CREDENTIALS__CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}
      DBT_HOST: ${DBT_HOST}
      DBT_USER: ${DBT_USER}
      DBT_PASSWORD: ${DBT_PASSWORD}
      DBT_PORT: ${DBT_PORT}
      DBT_DBNAME: ${DBT_DBNAME}
      DBT_SCHEMA: ${DBT_SCHEMA}
    volumes:
      # Existing data mount
      - ./data_extraction/Data:/pipeline/data_extraction/Data

      # Additional volumes for runtime editing and live data
      - ./data_extraction:/pipeline/data_extraction
      - ./postgres_dbt:/pipeline/postgres_dbt
      - ./orchestration:/pipeline/orchestration

      # Mount dbt profile directly 
      - ./postgres_dbt/profiles.yml:/root/.dbt/profiles.yml

      # Mount global data directory 
      - ./data:/pipeline/data

      # Mount requirements file for live dependency changes
      - ./requirements.txt:/pipeline/orchestration/requirements.txt

      # Mount .env file for consistent runtime environment
      - ./.env:/pipeline/.env

    expose:
      - 3001
    depends_on:
      - postgres_etl
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dwh-pipeline.rule=Host(`elt.zamdatalabs.com`)"
      - "traefik.http.routers.dwh-pipeline.entrypoints=websecure"
      - "traefik.http.routers.dwh-pipeline.tls.certresolver=letsencrypt"
      - "traefik.http.services.dwh-pipeline.loadbalancer.server.port=3001"
        # Auth (forces browser popup)
      # - "traefik.http.middlewares.dwh-pipeline-auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      # - "traefik.http.routers.dwh-pipeline.middlewares=dwh-pipeline-auth@docker"
      # HTTP â†’ HTTPS redirect
      - "traefik.http.routers.dwh-pipeline-redirect.entrypoints=web"
      - "traefik.http.routers.dwh-pipeline-redirect.rule=Host(`elt.zamdatalabs.com`)"
      - "traefik.http.routers.dwh-pipeline-redirect.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  postgres_etl:
    image: postgres:latest
    container_name: postgres_etl
    environment:
      POSTGRES_USER: ${DBT_USER}
      POSTGRES_DB: ${DBT_DBNAME}
      POSTGRES_PASSWORD: ${DBT_PASSWORD}
    volumes:
      - etl_pgdata:/var/lib/postgresql/data
    networks:
      - dokploy-network

volumes:
  etl_pgdata:

networks:
  dokploy-network:
    external: true
